FROM golang:1.22-alpine AS builder

WORKDIR /app
COPY go.mod go.sum* ./
RUN go mod download || true

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /bin/proxy cmd/proxy/main.go

FROM alpine:latest
WORKDIR /
COPY --from=builder /bin/proxy /proxy

EXPOSE 8080
ENTRYPOINT ["/proxy"]
